-- Enable Row Level Security (RLS) is good practice, but for simplicity in this starter
-- we will just create the tables. You can enable RLS later in the dashboard if needed.

-- 1. Artworks Table
create table if not exists artworks (
  id bigint generated by default as identity primary key,
  title text not null,
  year text,
  medium text,
  image_url text, -- We will store the full public URL here
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Exhibitions Table
create table if not exists exhibitions (
  id bigint generated by default as identity primary key,
  title text not null,
  location text,
  year text,
  dates text,
  link text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Subscribers Table
create table if not exists subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable Storage
-- You will need to create a storage bucket named 'artworks' in the Supabase Dashboard.
-- Go to Storage -> Create a new bucket -> Name: "artworks" -> Public: true
